setClass("myDate")
setClass("myTime")
setAs("character","myDate", function(from) as.Date(from, format="%d/%m/%Y") )
setAs("character","myTime", function(from) strptime(from, format = "%H:%M:%S") )
febData <- data.frame(subset(read.table("household_power_consumption.txt", sep=";", na.strings = "?", colClasses = c("myDate", "myTime", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), header = TRUE),  as.Date(Date) >= "2007-02-01" & as.Date(Date) <= "2007-02-02"))
febData <- within(febData, { timestamp=as.POSIXct(paste(Date, format(Time, format="%H:%M:%S")), "%d/%m/%Y %H:%M:%S") })
png("plot4.png", width = 480, height = 480)
par(mfcol=c(2,2))
plot(febData$timestamp, febData$Global_active_power, xlab="", ylab = "Global Active Power", type = "l")
plot(febData$timestamp, febData$Sub_metering_1, xlab="", ylab = "Energy sub metering", type = "l", col="black")
lines(febData$timestamp, y=febData$Sub_metering_2, col="red")
lines(febData$timestamp, y=febData$Sub_metering_3, col="blue")
legend("topright", lty=c(1,1,1), lwd = 1, legend = c("Sub_metering1", "Sub_metering2", "Sub_metering3"), col = c("black", "red", "blue"), bty = "n")
plot(febData$timestamp, febData$Voltage, xlab="datetime", ylab = "Voltage", type = "l", col="black")
plot(febData$timestamp, febData$Global_reactive_power, xlab="datetime", ylab = "Global_reactive_power", type = "l", col="black")
dev.off()