setClass("myDate")
setClass("myTime")
setAs("character","myDate", function(from) as.Date(from, format="%d/%m/%Y") )
setAs("character","myTime", function(from) strptime(from, format = "%H:%M:%S") )
febData <- data.frame(subset(read.table("household_power_consumption.txt", sep=";", na.strings = "?", colClasses = c("myDate", "myTime", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), header = TRUE),  as.Date(Date) >= "2007-02-01" & as.Date(Date) <= "2007-02-02"))
febData <- within(febData, { timestamp=as.POSIXct(paste(Date, format(Time, format="%H:%M:%S")), "%d/%m/%Y %H:%M:%S") })
png("plot2.png", width = 480, height = 480)
plot(febData$timestamp, febData$Global_active_power, xlab="", ylab = "Global Active Power (kilowatts)", type = "l")
dev.off()